# Generated by Django 3.1.1 on 2020-11-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201128_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckout',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer'),
        ),
    ]
