# Generated by Django 3.1.1 on 2020-11-28 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0009_ordercheckout_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercheckout',
            name='customer',
        ),
        migrations.AddField(
            model_name='ordercheckout',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
