# Generated by Django 3.1.1 on 2020-11-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201128_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercheckout',
            name='user',
        ),
        migrations.AddField(
            model_name='ordercheckout',
            name='useremail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ordercheckout',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='items_json',
            field=models.CharField(max_length=50000),
        ),
    ]
