# Generated by Django 3.1.3 on 2020-11-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201128_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckout',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
