# Generated by Django 3.1.3 on 2020-11-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_ordercheckout_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckout',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
